### PR TITLE
Support to dropdown menus

### PR DESCRIPTION
**Pull request by mrosso10**
# Summary
- Added a javascript file to be loaded in active_admin.js.coffee
- Added support to navbar's dropdown menus

Related issue: https://github.com/vinhnglx/active_bootstrap_skin/issues/4

### CODE REVIEW

**Comment by vinhnglx** [comment]
@mrosso10 thanks for your PR. But, when I test your PR on my local, I don't see any class `has_nested`. So the code doesn't work. Could you please check this PR again?

**Comment by mrosso10** [comment]
Oh, I will. Maybe we have different ActiveAdmin versions. I'll check it out.

**Comment by mrosso10** [comment]
@vinhnglx In which versions of Rails and ActiveAdmin did you try it?

**Comment by vinhnglx** [comment]
@mrosso10 

```
Rails 4.2.5
ActiveAdmin 1.0.0.pre2
```

**Comment by vinhnglx** [comment]
@mrosso10 hey man, you can check my PR #8

**Pull request closed without merging**
